<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NelderimCommon\NelderimCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\background.png" />
        <EmbeddedResource Include="Resources\discord.png" />
        <EmbeddedResource Include="Resources\Footlight-mt-light.ttf" />
        <EmbeddedResource Include="Resources\launch.png" />
        <EmbeddedResource Include="Resources\logo.png" />
        <EmbeddedResource Include="Resources\patreon.png" />
        <EmbeddedResource Include="Resources\www.png" />
        <EmbeddedResource Remove="output\**" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Hexa.NET.ImGui" Version="2.2.9" />
      <PackageReference Include="Hexa.NET.ImGui.Backends.SDL3" Version="1.0.18" />
      <PackageReference Include="Hexa.NET.SDL3" Version="1.2.17" />
      <PackageReference Include="Hexa.NET.Utilities" Version="2.2.12" />
    </ItemGroup>
</Project>
