<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
        <OutDir>output</OutDir>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\external\FNA\FNA.Core.csproj" />
      <ProjectReference Include="..\external\ImGui.NET\src\ImGui.NET\ImGui.NET.csproj" />
      <ProjectReference Include="..\NelderimManifestUpdate\NelderimManifestUpdate.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\background.png" />
        <EmbeddedResource Include="Resources\discord.png" />
        <EmbeddedResource Include="Resources\Footlight-mt-light.ttf" />
        <EmbeddedResource Include="Resources\launch.png" />
        <EmbeddedResource Include="Resources\logo.png" />
        <EmbeddedResource Include="Resources\patreon.png" />
        <EmbeddedResource Include="Resources\www.png" />
    </ItemGroup>
    
    <PropertyGroup Condition="$(RuntimeIdentifier) != '' or $(RunnerOs) != ''"> <!-- publish -->
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>false</SelfContained>
        <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    </PropertyGroup>
    
    <ItemGroup Condition="$(RuntimeIdentifier) == 'win-x64' or $(RuntimeIdentifier) == '' or $(RunnerOs) == 'Windows'">
        <DataFiles Include="..\external\fnalibs\x64\*.*"/>
    </ItemGroup>

    <ItemGroup Condition="$(RuntimeIdentifier) == 'linux-x64' or $(RuntimeIdentifier) == '' or $(RunnerOs) == 'Linux'">
        <DataFiles Include="../external/fnalibs/lib64/*.*"/>
    </ItemGroup>
    
    <ItemGroup Condition="$(RuntimeIdentifier) == 'osx-x64' or $(RuntimeIdentifier) == '' or $(RunnerOs) == 'macOS'">
        <DataFiles Include="../external/fnalibs/osx/*.*"/>
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Hexa.NET.ImGui" Version="2.2.9" />
      <PackageReference Include="Hexa.NET.ImGui.Backends.SDL3" Version="1.0.18" />
    </ItemGroup>

    <Target Name="Copy_build" AfterTargets="Build">
        <Copy SourceFiles="@(DataFiles)"
              DestinationFiles="@(DataFiles->'$(OutDir)/%(RecursiveDir)%(Filename)%(Extension)')"
              SkipUnchangedFiles="true"/>
    </Target>

    <Target Name="Copy_publish" AfterTargets="Publish">
        <Copy SourceFiles="@(DataFiles)"
              DestinationFiles="@(DataFiles->'$(PublishDir)/%(RecursiveDir)%(Filename)%(Extension)')"
              SkipUnchangedFiles="true"/>
    </Target>
</Project>
