name: Build & Release

on:
  push:
    branches: "master"
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: "*"
    paths-ignore:
      - '**/README.md'
  

env:
  DOTNET_NOLOGO: false
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ windows-latest, ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Publish
        run: dotnet publish NelderimLauncher -c Release -o release -p:DebugType=None
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: NelderimLauncher-${{ runner.os }}-${{ runner.arch }}
          path: ${{ github.workspace }}/release/NelderimLauncher.exe
